### ISSUE TITLE
Installation Prerequisites

### ISSUE THREAD

**Issue by abebeos** [gmelillo/helm-charts#48]
mailu lacks documentation on how to install the prerequisites (cert-manager, ingress/nginx etc.) on a fresh k8s cluster:

https://github.com/Mailu/helm-charts/blob/master/mailu/README.md#prerequisites

What are the prerequisites for this mailu version? Any suggestions for a simplified setup?

**Comment by gmelillo** [comment]
At the moment is mostly like the official one, the big change is that can be used on hybrid clusters (ARM + AMD CPU).
To actually deploy to a kubernetes cluster you need to point your local DNS to a DNSSEC capable DNS as an upstream.

I'm using it as a temporary one to allow my deployment on that type of cluster, in the future I hope I can deprecate this version in order to switch back to the official one.

you can point your `coredns` with `forward . X.X.X.X`

**Comment by abebeos** [comment]
The additional ARM support is nice. 

But the thing is: installing via helm is trivial, but there is zero docs about setting up the required stuff (cert-manager, ingress/nginx, the DNSSEC you mention).

So my understanding is that your version does not have any documentation about this, too? (thus people not very familiar with this stuff don't "fight" for days...)

**Comment by gmelillo** [comment]
Correct, at the moment it is missing that part of documentation
